import '../scss/index.scss'
import './swiper-slider.js'
import './showTabContent.js'
import './showCategories.js'
import './closeCategories.js'
import './selectDescription.js'
import './selectCategories.js'